### ISSUE TITLE
Add an validation info for image uploads 

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#146]
When adding a picture to a proposal that does not match the 1300 pixels, the attachment is deleted and an error occurs. Would we mention that any picture upload should be 1300 pixels wide somewhere? 

![bildschirmfoto 2016-07-20 um 13 42 24](https://cloud.githubusercontent.com/assets/13625047/16985438/a6b0cc5c-4e80-11e6-9863-a1121c8378d8.png)

**Comment by MagdaN** [comment]
@NadineKarbach yes, good point, @nicoladimarco should I add help texts
