### ISSUE TITLE
(Mobile) Edit and delete of proposal not possible

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#147]
I tested to edit or to delete my proposal on my iPhone 5s after i was logged in and it did not worked. There was no error message. I stayed on the same side. 

![edit not possible](https://cloud.githubusercontent.com/assets/13625047/16987009/1b3a00b2-4e8a-11e6-8027-90ff52b549b0.png)

**Comment by MagdaN** [comment]
same with me
