### ISSUE TITLE
(Mobile) If inserting link, the screen allows no interaction anymore

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#149]
I tested to insert a link. The menu looks elaborated and i am happy with what kind of links i can insert. Yet, i can not close the window and return to the field where i entered my proposal. Even though here it shows the "ok" button in green, by clicking on it, nothing happens and i remain on the same screen.

![if inserting link](https://cloud.githubusercontent.com/assets/13625047/16987108/cb08d5c2-4e8a-11e6-895f-413fd9a64f37.png)

**Comment by MagdaN** [comment]
@NadineKarbach can't reproduce, please show me :-)
