### ISSUE TITLE
Rate widgets might be confusing

### ISSUE THREAD

**Issue by slomo** [liqd/euth_wagtail#179]
The rate widget in the comment listing and idea listing look alike, but they be have differently. In comments listing the user can click to vote, while in the idea listing she can not. 

---
![Comment listing](http://image.prntscr.com/image/d99e0e17d8f34b90839e24501ae77bdc.png)
![Idea listing](http://image.prntscr.com/image/740df91b64e3400cbc3a3db1ff82b724.png)

---

There exists a third widget in the idea detail view, it can be used to vote.

---
![idea detail view](http://image.prntscr.com/image/9e449997630542eb89aae398d356b307.png)

---
I propose to replace the widget in the commenting listing with one that looks more like detail listing one.

Additional thoughts:

- I'd like if we cut down the number of widgets in general
- I'd like if clickable elements would change a little bit on `hover` and `active` to have some guidance for the user here

**Comment by nicoladimarco** [comment]
better?
https://marvelapp.com/17ha8g1#14446738

**Comment by slomo** [comment]
Thanks for the feedback @nicoladimarco, just to summarise what changes I can see from those screens:

The three rate widgets above now all have a commonly styled indicator to display what the user has voted.

Which is already at least 50 % to where I wanted to go :smile:. I have troubles understanding possible interactions by looking at the marvel app. Is it possible to vote up/down by clicking on the red and green arrows in the idea list item? And if not why do those arrows look the same as in the comment list view, where it is possible to vote up/down by clicking on the arrows?

**Comment by nicoladimarco** [comment]
@slomo I think I´ve found a better solution now: as you suggested the buttons look the same on the proposal and on the comment since you can interact with both of them but differently on the list Item since they are just showing the number of votes but the user cannot interact with them.

https://marvelapp.com/17ha8g1#14446738

**Comment by slomo** [comment]
That would solve exactly what I wished for. So we should apply that solution some where.

**Comment by vellip** [comment]
This has been added already; Mobile will be worked on in #211.
