### ISSUE TITLE
FK-Fields to a user in Models should all have the same name 

### ISSUE THREAD

**Issue by MagdaN** [liqd/euth_wagtail#184]
We different models which all save a user as creator, but the fields are named differently (user, creator, ...) 
I would suggest to always call them creator. Maybe we could also implement a abstract model with a creator field and make the other models inherit from this abstract model.

**Comment by keimlink** [comment]
The abstract creator model sounds like a great idea! 👍

As a temporary fix a `creator` property could be used which returns the appropriate field value. What do you think @MagdaN?

**Comment by MagdaN** [comment]
@keimlink yeah thats also a good fix

**Comment by slomo** [comment]
I quess we could name the abstract model UserGeneratedContent ?
