### ISSUE TITLE
Password reset button not styled properly

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#194]
The reset button when trying to reset my password does not look like they conform to our standard buttons on OPIN. Could you check the design, please?
![bildschirmfoto 2016-08-18 um 18 06 14](https://cloud.githubusercontent.com/assets/15341015/17781247/ded2f6f0-656e-11e6-8d07-bef6469884f1.png)

**Comment by vellip** [comment]
Should rather look like this button: https://app.zeplin.io/project.html#pid=577bac98e7368b235604d8a2&sid=578cc61f2846d91408078554
