### ISSUE TITLE
No warning/help text when password entered incorrectly

### ISSUE THREAD

**Issue by rukala** [liqd/euth_wagtail#198]
When I try to log in with the wrong log in details, I don't get a message informing me what didn't work - i.e. wrong password/log in (Firefox, 47 on Mac).

**Comment by slomo** [comment]
The login code is supposed to work that way, so that no hint is given whether the username or password is the issue. I would support a change that behaviour.

I would recommend to support those error messages:
 - user name not known
 - user not activated
 - password wrong
