### ISSUE TITLE
Profile: Showing the avatar image and URL

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#210]
Currently we show the URL of the avatar image in https://opin-dev.liqd.net/de/dashboard/profile/ once you have uploaded an avatar image. Two remarks
1. We should only show the filename of the current avatar image not the URL on the server
2. We should also show the actual image that is currently used not just the URL/filename

**Comment by slomo** [comment]
Should be fixed one is merged #168

**Comment by slomo** [comment]
Fixed
