### ISSUE TITLE
Voting buttons look different on Mobile

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#211]
The voting buttons look different on Mobile Safario (Tested on iOS 9.3.3.) from the desktop versions. The buttons have no spacing in between and they still have rounded corners.

![foto 24 08 16 10 41 11](https://cloud.githubusercontent.com/assets/15341015/17924129/a6c2db90-69e7-11e6-836c-d9b954d771e5.png)

**Comment by vellip** [comment]
This is not only showing on iOS, Voting buttons design is in #179, mobile was not considered there, so I guess, they should look exactly the same there.

**Comment by slomo** [comment]
@rittermo Can't validate due to not having an iOS device

**Comment by vellip** [comment]
To be precisely, it will be fixed with #233.
