### ISSUE TITLE
Open styling issues

### ISSUE THREAD

**Issue by slomo** [liqd/euth_wagtail#221]
- [x] Image upload widget #168 
- [x] Implemented proper tabs (with hash) in project overview
- [x] check implemented views against click dummy/designs
  - [x] login / register
  - [x] reset password dialog
  - [x] reset password email
  - [x] activation email
  - [x] organisation page
  - [x] project detail (if no module has been created)
  - [x] idea collection overview (info/ particpate)
  - [x] create/modify idea 
  - [x] comment listings
  - [x] report comments modal
  - [x] report emails (to user and admin)
  - [x] delete comment modal

**Comment by vellip** [comment]
@rittermo, @NadineKarbach you can have a look at those.
