### ISSUE TITLE
Reset email shows example.com as domain

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#287]
The password reset email shows “example.com” instead of the correct OPIN domain as the domain in the subject line and email text.

<img width="966" alt="bildschirmfoto 2016-09-12 um 09 24 37" src="https://cloud.githubusercontent.com/assets/15341015/18427917/46a89d88-78cb-11e6-88bb-7bd189a0e0de.png">

**Comment by slomo** [comment]
This can be configured from the django admin, by editing the "Site" object in the django-admin (I fixed it for staging).
