### ISSUE TITLE
Issues after replacing euth_users with allauth views

### ISSUE THREAD

**Issue by slomo** [liqd/euth_wagtail#306]
- [x] dashboard email addresses (styling)
- [x] dashboard account connection (styling)
-  ~~merge email addresses and account connection with profile~~
- [x] password reset form (styling)
- [x] login / logout forms have two labels for each field
- [x] login form login buttons for all providers (styling)
  - if this could be somewhat dynamic ;)
- [x] automatic login after confirming email address
- [ ] track `next` action through confirming email address (might be hard)
- [ ] track `next` action through social login (might be hard)
- [x] don't verify email address after social login
- [x] fix encoded html entities (`"Successfully signed in as philippveller2 &lt;[...]&gt;."`)
- [x] fix emails to be sent as HTML again

**Comment by vellip** [comment]
Ad 3: Email Addresses are already done (the old view needs to be removed still, and then the action attribute for the particular form needs to be changed so the user stays on the page after submitting, Account connections don't work as easily, the form is bound to the allauth view currently)

**Comment by slomo** [comment]
Together with @vellip @NadineKarbach @rittermo and me it has been decided that we won't merge email change / social connect views. Instead we will split the dashboard menu in an organisation specific section and a user specific section (called user settings).
