### ISSUE TITLE
Do not redirect to project page after edit

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#319]
When I edit project info (for example the project title) in the dashboard and click on “save and publish”, I am redirected to the project page in the frontend. 
https://opin-stage.liqd.net/de/dashboard/sample-organisation/projects/sample-idea-collection/

It would be nice to just reload the form and a message on top of it “Your changes have been saved. Visit the <link to project page>project page</link to project page> to see them.“ This would make it possible to edit other things and not have to navigate back to the dashboard again, while also giving the option to review the changes via the link.

**Comment by vellip** [comment]
Please try to check this on dev. We noticed the same and already changed it
accordingly once.

**Comment by slomo** [comment]
Should be solved on opin-dev
