### ISSUE TITLE
organization logo styling bugs

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#336]
The way orga logos are shown has some minor issues:

- [x] On the project page the logo is not shown (blank white circle): https://opin.me/de/projects/commenting-text/
- [x] The logo should have more padding from the edges of the white circle on the project page (just like it does on the tiles for an organization on the organization overview page): https://opin.me/de/orgs/conseil-parisien-de-la-jeunesse/
- [ ] Logos in bigger format on the organization page look blurry – even on non-high-res screens: https://opin.me/de/orgs/opin-examples/

**Comment by MagdaN** [comment]
@rittermo the last example is the default logo that is only displayed, when no logo has been uploaded, do you have another example?

**Comment by MagdaN** [comment]
@slomo @vellip the logo on the organisation page is cropped to 200x200 px maybe that is too small?
