### ISSUE TITLE
improvements for orga info in dashboard

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#337]
Some issues with how texts and info on organizations are edited (see https://opin.me/de/dashboard/opin-examples/)
- [x] The title of the page should be “Edit your organisation information“ instead of “Edit a project”
- [x] The label of the submit button of the form should be changed to “Save changes“
- [x] The info underneath the upload fields should read “You’re image will be uploaded/removed once you click “save changes” at the end of this page.” instead of  “Please hit the post button to save your changes.”
- [x] Currently,there is a 400 chars limit in the dashboard for texts that are entered for an organization. This should be changed to 1000 chars
- [x] The fields for the organization texts “Description”, “Description how” and “Description why” should be changed to the order of how they are shown on the organization page : Why; How; Descr.
- [x] The fields for the organization texts “Description”, “Description how” and “Description why” should be textareas that have a standard height of 4 lines of text
- [x] Rename the fields for orga texts: “Description” should be renamed to “More info about the organisation / Short text for organisation overview” 
- [x] The preview of the uploaded orga logo should be smaller (max 250px width) and (nice to have) it should be floated to the left of the logo upload form field
- [x] The menu item in the dashboard nav for this page should be called “Organisation information“ instead of “Organisations”
- [x] The label “Image” should be changed to “Header Image”
- [x] There should be an info box underneath the image upload fields that informs on the required file format, max. file size and dimensions of the image; could be maybe combined with the save changes button info (see above)
- [x] The “Title”label for the form field should be renamed to “Title of the organization”

**Comment by MagdaN** [comment]
@rittermo I changed the text for the image upload to 'You’re image will be uploaded/removed once you save your changes at the end of this page.' because this text is shown underneath all image uploads (also in other forms) and we don't the text on the button,

**Comment by MagdaN** [comment]
@rittermo 'Organisation information' is a bit too long, so I just changed it to 'Information'. I think as it is in the 'Organisations settings' it should be ok.
