### ISSUE TITLE
Choose template: Small issues

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#339]
There are some small wording issues when you choose a template to create a project in the dashboard. See comments in screenshot.

![unknown-18](https://cloud.githubusercontent.com/assets/15341015/18997556/467cc690-8735-11e6-9764-b150f0865098.png)

**Comment by slomo** [comment]
Does this imply that all pages under reachable from the projects page, should highlight the corresponding menu item? Because they don't currently (eg project creation form, project update form, project user management).

**Comment by slomo** [comment]
Same goes for '<- back to project' or similar buttons, should they be added to each dashboard view?

**Comment by MagdaN** [comment]
@rittermo what do you think?
