### ISSUE TITLE
Markdown in comments in consistent with rest

### ISSUE THREAD

**Issue by slomo** [liqd/euth_wagtail#363]
We decided against Markdown in most of the other input fields and used CKEditor instead, but comments still use markdown. But this is not document anywhere. So these are our options:
1. support markdown in comments, but also advertise it to the user
2. support only new lines and nor further formatting in comments (like _italic_, **bold**, ~~strike~~)
3. add ckeditor to comment edit field and allow some basic html in comments

**Comment by slomo** [comment]
Since this is more a product decision than technical I like to have feedback from @rittermo and @NadineKarbach first, before choosing a solution.

**Comment by NadineKarbach** [comment]
Hey, Option 1 seems suitable for me, i i would decide for one. But @rittermo has a deeper insight int o the product development here. // @slomo
