### ISSUE TITLE
Change "phases" to "phase" in Commenting text and Mobile Polling in Dashboard

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#368]
Hey :) when initiating a commenting text or a mobile polling project in the dashboard, it says "the resulting project will have 1 phases". Maybe we can change that to ".....contain 1 phase".? Thanks

![bildschirmfoto 2016-10-19 um 12 47 25](https://cloud.githubusercontent.com/assets/13625047/19516060/8cfc07f6-95fa-11e6-9c28-f419361e696d.png)

**Comment by slomo** [comment]
Fixed in f431a58
