### ISSUE TITLE
(Mobile) No date visible  in list view of proposals 

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#371]
Hey A-Team, when scrolling the list view of proposals the date of the proposal below the creator is not visible. Is there a chance to fix that? (iPhone 5s, Safari) Thanks :) 

![list view of proposals broken](https://cloud.githubusercontent.com/assets/13625047/19520872/f5b374f2-9611-11e6-9c69-68c9bfded661.PNG)

**Comment by MagdaN** [comment]
tested this on android - cannot reproduce problem

**Comment by MagdaN** [comment]
yes, we could reproduce the problem
