### ISSUE TITLE
Private Project - Not able to join after receiving an invitation

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#377]
Hey A-Team, based on an experience by our pilot AEGEE, i tried to reproduce a problem they faced. Here is what i found.
Project: Test Idea Collection OPIN 1.5 by AEGEE
Procedure: me1 (nadine.karbach@liqd.de) invited me2 (nadine.karbach+4@liqd.de) to join this private project. 
me2 received an email with the invitation. 
me2 clicked on it and registered on OPIN. 
me2 received an email that me2 should check the mailbox for activating the account. 
me2 did activate the account. 
me2 clicked again on the invitation link in the email. 
me2 got directed to the private project.
me2 clicked on "accept" to join the project (top screenshot).
me2 got the message "403 forbidden" (bottom screenshot).

I attach you the screenshots i made to illustrate some steps.
Any idea why me2 cannot access the private project of AEGEE?

Thanks a lot! me1 and me2 ;) 

![bildschirmfoto 2016-10-20 um 16 48 30](https://cloud.githubusercontent.com/assets/13625047/19566029/33aed044-96e9-11e6-9c23-b6d6e0c8dd3f.png)

![bildschirmfoto 2016-10-20 um 16 49 41](https://cloud.githubusercontent.com/assets/13625047/19566046/3cf5f0ce-96e9-11e6-992b-8a6689f0c127.png)

**Comment by slomo** [comment]
I think the project is still in draft. Publishing the project will fix the particular error, but we should address the error it self.

There are two options here:

- don't allow invites to projects in draft, by removing the button from the user management view
   (might run into errors if a project is unpublished again)
- display a more helpful error page to users
   (leaves the user in position where they might be all hot and ready for participation, but they can't)

**Comment by slomo** [comment]
Any updates here?

**Comment by NadineKarbach** [comment]
@slomo hey, i received an email from AEGEE to test their private project. Will try to follow this till the end of the this week.

**Comment by vellip** [comment]
@NadineKarbach Since there was a small change made to how we handle the process after registering this could be checked again now. Is there any feedback already or is it possible to get feedback on it?
