### ISSUE TITLE
create project in dashboars: info texts and headlines 

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#379]
The form labels and descriptions in the info tab are very important as there is info for the project in general and the info tab that needs to be given. I created some new labels, descriptions and placeholder texts as well as two headlines in the forms that will hopefully explain it a bit better to users.

**Comment by MagdaN** [comment]
@damusp can you upload the file to zeplin

**Comment by MagdaN** [comment]
@rittermo can you provide the texts

**Comment by MagdaN** [comment]
Helptexts are added by #397

**Comment by vellip** [comment]
Texts are there. Still missing: Headlines. @damusp Please think about the headline/section style once more as discussed.

**Comment by damusp** [comment]
As Magda suggested, I reduced the number of styles used for headlines. Files have been uploaded to Zeplin.
