### ISSUE TITLE
Fixed header anchor issues

### ISSUE THREAD

**Issue by slomo** [liqd/euth_wagtail#409]
With the fixed header we usually have the problem, that setting an anchor will always result in the top part of the page being hidden away under the header. We could deploy a general fix for this in css:

```
:target:before {
     content:"";
     display:block;
     height:90px; /* fixed header height*/
     margin:-90px 0 0; /* negative fixed header height */
}
```

[source](https://www.itsupportguides.com/tech-tips-tricks/how-to-offset-anchor-tag-link-using-css/)

I can imagine that this might lead to issues if we don't know the size of our fixed header (due to zooming, too long menu items or responsiveness). But we could evaluate it at least. It would be also interesting what the implications for accessibility are.

**Comment by vellip** [comment]
I don't see this as such a big problem yet. And using this solution, we might have our content jumping up and down, which would annoy more.
