### ISSUE TITLE
Project description field styled unregular

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#433]
Hi there, the project description boxes from the Italian pilots don't have the same size/height. It would look nicer when all boxes had the same format/size. Thanks!

![bildschirmfoto 2016-11-02 um 11 48 59](https://cloud.githubusercontent.com/assets/13625047/19926102/1183b890-a0f3-11e6-9730-dec664aee131.png)

**Comment by vellip** [comment]
The problem doesn't show up on opin.me right now, and if it does again that's just how it is. The only solution would be to make all tiles taller but after talking to @damusp we came to the conclusion this is not desirable.
