### ISSUE TITLE
carousel on home page extends beyond page width

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#441]
Currently the carousel on https://opin-dev.liqd.net/de/ extends beyond the page with and creates an unsightly overhang that scrolls. The problem seems to be only present in Safari (tested on version 10). In Firefox 47 the carousel seemed fine.
![bildschirmfoto 2016-11-03 um 10 11 16](https://cloud.githubusercontent.com/assets/15341015/19960616/4165d122-a1ae-11e6-9154-34cd25841ebf.png)

**Comment by vellip** [comment]
overflow-x: hidden on html would solve it. But I don't necessarily like this solution because it hides every other overflow problem we might have without solving it

**Comment by rittermo** [comment]
As discussed: 
- please put another wrapper around it to hide the overflow
- the carousel should start at the most recent project
