### ISSUE TITLE
create proposal button on finished module

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#442]
On this project https://opin-dev.liqd.net/de/projects/quod-facere-quas/ there is a create proposal button although the project notice says that participation is finished. 
![bildschirmfoto 2016-11-03 um 10 14 37](https://cloud.githubusercontent.com/assets/15341015/19960688/93bab942-a1ae-11e6-9f55-d7ac552425e7.png)

**Comment by MagdaN** [comment]
@rittermo I think you are logged in as admin or moderator, then you can alway add ideas

**Comment by rittermo** [comment]
Ah okay! Thanks for the explanation @MagdaN. Then we need some vertical spacing for the button, so that it doesn’t stick to the intro text too much.
