### ISSUE TITLE
Homepage and project detail: Make text on header semi-bold

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#466]
The description that sits on top of the header image is barely readable, especially when busy images are used (see homepage). The text should be set in semi-bold.
![bildschirmfoto 2016-11-10 um 17 47 53](https://cloud.githubusercontent.com/assets/15341015/20185886/219a9150-a76e-11e6-9da1-5c9c0513f23d.png)

**Comment by vellip** [comment]
is like that already for a while
