### ISSUE TITLE
Add picture in CKEditor in Commenting text

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#485]
Hey, hey, it would be fine and nice to enable the function of including pictures in the CKEditor in the Commenting text. This is of particular interest of our Pilot Heart of Slovenia: They have text that is related to pictures and they want to get young people'si ideas on it. Great thanks :)

**Comment by rittermo** [comment]
We just discussed this in the stand-up. The images you upload via the CKEditor are not private, which would mean anyone could access them via the URL, even if the image is in a private project. Therefore,  this is more a user story than an issue in terms of effort. Is solving this very urgent, @NadineKarbach? I think we could put a user story in the next sprint.

**Comment by NadineKarbach** [comment]
@rittermo hey, just read it now. The Heart of Slovenia is an open project, in this particular case it would not matter whether it is accessible for everyone. I can write a US for it and communicate back to HoS that it is not easy to solve it "by the way". Thanks :)

**Comment by NadineKarbach** [comment]
Hey there, I added this to a US as suggested above. It is this one https://tree.taiga.io/project/evpa-euth/us/790?no-milestone=1 Not urgent and in the dimension of "OPIN improvements". Thanks :)
