### ISSUE TITLE
All recipients visible in email when project is deleted

### ISSUE THREAD

**Issue by MagdaN** [liqd/euth_wagtail#495]
email adds all recipients to 'to'

**Comment by vellip** [comment]
Mails are now sent one by one.

**Comment by MagdaN** [comment]
issue is not fixed

**Comment by slomo** [comment]
I added a pr for this to adhocracy4 (https://github.com/liqd/adhocracy4/pull/36)

**Comment by slomo** [comment]
PR has been merged need to update A4 version

**Comment by slomo** [comment]
Solved with #695
