### ISSUE TITLE
readability on project page

### ISSUE THREAD

**Issue by damusp** [liqd/euth_wagtail#517]
Some elements like the phase description are difficult to read due very long lines of text. 

![bildschirmfoto 2016-11-25 um 13 40 27](https://cloud.githubusercontent.com/assets/22769111/20626048/3fefa7f8-b317-11e6-9bbc-f82e76f05418.png)

**Comment by slomo** [comment]
What would be your favourite solution here? Increase padding/margin or introduce columns?

**Comment by damusp** [comment]
I'm planning to put the headline and description text inside a div with .container-medium

**Comment by damusp** [comment]
(actually I did exactly that last friday, but I kind of messed up the branch and had to delete it. I'll be able to fix it soon though!)
