### ISSUE TITLE
Change placeholder text if user has no projects

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#547]
Currently, placeholder text in the user profile if a user has no projects to show is slightly misleading. It should be “username follows no projects at the moment.” instead.

![bildschirmfoto 2016-12-07 um 17 24 08](https://cloud.githubusercontent.com/assets/15341015/20976265/4a64dbce-bca2-11e6-8c1c-185b6bf4d03c.png)

**Comment by slomo** [comment]
Fixed in d5e0d60
