### ISSUE TITLE
Typo User settings in Dashboard

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#553]
Hi A-team, a space in between receive and notifications would be marvelous. Great thanks!
Discovered on "stage".

![bildschirmfoto 2016-12-12 um 17 19 56](https://cloud.githubusercontent.com/assets/13625047/21106727/6320e4be-c08f-11e6-95a0-9990b7b87d3f.png)

**Comment by slomo** [comment]
Fixed in 6f821b893f78dfa00b8166204f43d8c6589e6156
