### ISSUE TITLE
Twitter birds might need some air to breath

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#555]
Hey A-Team, on the mobile version, the twitter bird is very close to the avatar picture. Maybe he needs more space? 
Would the information below look better if centered? (city of residence,..)

![img_2898](https://cloud.githubusercontent.com/assets/13625047/21222725/9f2036f0-c2c3-11e6-9b02-e7aa7867102c.PNG)

**Comment by MagdaN** [comment]
also interesting: Nadine should not be 0 years old
