### ISSUE TITLE
new users cannot create idea on opin dev

### ISSUE THREAD

**Issue by MagdaN** [liqd/euth_wagtail#570]
users who register on opin-dev cannot create idea

**Comment by stadine** [comment]
@slomo ich möchte auch ideen anlegen! ich habe viele ideen. grüße.

**Comment by slomo** [comment]
Narrowed it down to: Users (non-admins) can't create ideas on maps, because the add button is not displayed and user seems not to have permission for object creation.

**Comment by slomo** [comment]
Should be fixed now!
