### ISSUE TITLE
Picture upload deleted when error for missing text

### ISSUE THREAD

**Issue by rukala** [liqd/euth_wagtail#589]
When I select a picture to upload in my idea and forgot to write a text, after posting I am reminded that entering a text is mandatory. Then my preselected image is lost.

**Comment by slomo** [comment]
This can not be done with server side rendering (at least to my knowledge) :crying_cat_face:, for reference see this [stackoverflow anwser](http://stackoverflow.com/a/5293998)

**Comment by slomo** [comment]
Closing for now. @NadineKarbach  @rittermo If this is important for you, we'll need a story.
