### ISSUE TITLE
Maps-Testing: Map takes whole screen on mobile and create problems in scrolling up/down

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#596]
Hi, when testing the maps on mobile, the map takes the whole screen. When I want to scroll up or down that page, I mainly scroll the map. It is working still, yet, it would be beneficial to have the map somewhat smaller in the mobile view, I can imagine. Great thanks! 

![img_2978](https://cloud.githubusercontent.com/assets/13625047/22017863/51406eca-dcac-11e6-9a46-cf2cd96fe72d.PNG)

**Comment by MagdaN** [comment]
@rittermo @damusp do you agree with this?
