### ISSUE TITLE
Maps-Testing: Edit and delete button cover title on mobile

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#598]
Hi, when I want to edit my proposal, the edit/delete function covers the title of my proposal. In general it looks a bit cut and big. What do you think? 

![img_2980](https://cloud.githubusercontent.com/assets/13625047/22021253/6612cbe4-dcbc-11e6-862d-82746c022f19.PNG)

**Comment by MagdaN** [comment]
I think there is not much we can do about this
