### ISSUE TITLE
Maps-Testing: View on mobile does not fill width of screen/ white spacing on right border

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#599]
Hi, I discovered that the width of OPIN is a bit smaller than the mobile screen. There is a white space on the right. Is it intended to be like this? Great thanks! 

![img_2981](https://cloud.githubusercontent.com/assets/13625047/22021296/a7ed61e6-dcbc-11e6-928d-11803a702689.PNG)

**Comment by MagdaN** [comment]
@NadineKarbach @vellip this is not a map problem but a problem with the slider
