### ISSUE TITLE
Heroku staging server uses forked buildpack

### ISSUE THREAD

**Issue by slomo** [liqd/euth_wagtail#60]
Features required from [non-official buildpack](/slomo/heroku-buildpack-python):

- `python manage.py bower install` run before collect static
- `python manage.py compress` run before collect static

First one can be mitigated by using npm for managing frontend dependencies.

**Comment by MagdaN** [comment]
@slomo can that be closed because we use webpack: https://github.com/liqd/euth_wagtail/pull/72

**Comment by slomo** [comment]
No there is still a change to the buildpack. We have to run compress in post_install.

**Comment by slomo** [comment]
We don't use heroku any more.
