### ISSUE TITLE
Facebook Login does not work

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#602]
When I try to login via FB on opin-stage https://opin-stage.liqd.net/accounts/login/?next=/de/dashboard/sample-organisation/projects/ , an error appears.

![bildschirmfoto 2017-01-19 um 15 53 13](https://cloud.githubusercontent.com/assets/15341015/22111417/8518c8aa-de5f-11e6-9d6e-f6b0c29267ff.png)

**Comment by vellip** [comment]
This is a problem for staging only.

**Comment by slomo** [comment]
Sollte behoben sein.
