### ISSUE TITLE
form validation error messages not very visible

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#628]
The error messages when you post incorrect info for a new proposal don’t stand out enough and the bullet points don’t make sense if there is just one error.

![bildschirmfoto 2017-01-24 um 14 27 30](https://cloud.githubusercontent.com/assets/15341015/22248999/7afe693e-e241-11e6-9af3-8d22784e37fe.png)

**Comment by rittermo** [comment]
@damusp could you come up with an idea for this?

**Comment by damusp** [comment]
@rittermo @vellip @MagdaN, what do you think about something like this? 

![alert_alert_alert_wheeoo](https://cloud.githubusercontent.com/assets/22769111/22250841/c29ad280-e248-11e6-8ff2-934e1b182f21.png)




We could also add a nice little animation to the icon (that's something we could pick up more in general for opin!) http://l-lin.github.io/font-awesome-animation/
