### ISSUE TITLE
Map validation error messages not understandable

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#639]
There is a message “Enter valid JSON for when location data is missing. I encountered the error message on two occasions:
1) When a participant posts a proposal without setting a location on the map
2) When an initiator does not define a polygon when configuring a spatial project

The messages should be more clear:
for 1) You need to locate your proposal on the map
for 2) You need to define an area for your project on the map

**Comment by slomo** [comment]
Would a more generic "This field is required" also be okay?

**Comment by slomo** [comment]
Discussed offline: At least for end-user dialog (eg. placing a pin in an idea collection) a better error message should be available.

**Comment by slomo** [comment]
Closed via #690
