### ISSUE TITLE
Invite: email address should be independent of letter case 

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#640]
After testing invites for private projects a lot with AEGEE, I finally found out what their problem was. When they invite users, the auto correct on their Android tablet lets email addresses start with an uppercase letter. The users they wanted to invite had their email address written in lowercase letters though. OPIN did not recognize them as the same users. We should change this behaviour ASAP. It should not matter anywhere whether a user inputs email addresses in lower or uppercase letters.

**Comment by slomo** [comment]
I think the fault lies in #605 it introduces a filter for user emails without doing email normalisation. I think we should revert the changes from #605.

**Comment by slomo** [comment]
As decided in an offline meeting I will roll back #605
