### ISSUE TITLE
Map shows multiple (alternative?) worlds

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#675]
When you zoom the OSM maps out, you can see more than one world map. I don’t dare to set markers on one of the alternative worlds for fear of a black hole or a gate to an alternative world. It happens on all instances of the map widget. Please fix!
![bildschirmfoto 2017-02-16 um 16 31 37](https://cloud.githubusercontent.com/assets/15341015/23027777/ae50292c-f465-11e6-9e14-ddecc5a4d0ab.png)

**Comment by slomo** [comment]
closed with #696
