### ISSUE TITLE
Phases: Show exact time for start and end

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#677]
For the start and end date, we should show the exact hour not just the date. Beware of the dreaded time zone problem. We should either:

- Show UTC time or
- Calculate the UTC in the local client time and show the client time

We should always show the time zone behind time given (i.e. „12:00 UTC“ or „12:00 GTM“ or whatever).

**Comment by slomo** [comment]
https://github.com/liqd/euth_wagtail/pull/683 enables to show the whole datetime. I think we should not add timestamps to each date. Maybe just some message in the footer.

**Comment by slomo** [comment]
@rittermo Can we consider this closed with #683
