### ISSUE TITLE
Title Case in buttons on opin-dev

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#678]
I see that on opin-dev, we now use title case for buttons. I think this is not ideal, since it is only common for English buttons. In German it creates a lot of problems, for example, because verbs can get mistaken as nouns and so on. Even in English, some words like “and” or “or” are not normally spelled with a capital letter in titles. I think the upper-case spelling was more reasonable for all languages.

![bildschirmfoto 2017-02-16 um 17 08 56](https://cloud.githubusercontent.com/assets/15341015/23029416/badf1d06-f46a-11e6-9c91-74605bed3dad.png)

**Comment by rittermo** [comment]
@damusp was this intentional?

**Comment by damusp** [comment]
Partly – we were thinking on how to make button styles more consistent. 
Title case is not ideal like you said, but I don't favor to use upper case in all our buttons for its heavy aestethic and bad legibility. 

<img width="1091" alt="bildschirmfoto 2017-02-17 um 10 07 13" src="https://cloud.githubusercontent.com/assets/22769111/23059687/c3dbd13e-f4fa-11e6-8bec-44612bcf5225.png">

What about having all buttons without any text transform property?

**Comment by rittermo** [comment]
@damusp Thanks for the explanation. I think your idea of using no text-transform is the best way, especially for multi-language web apps.
