### ISSUE TITLE
Assign moderator role: Adding moderators does not work

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#680]
![bildschirmfoto 2017-02-16 um 17 24 10](https://cloud.githubusercontent.com/assets/15341015/23030159/371e5be6-f46d-11e6-877c-bcae92e47a04.png)
When I want to add a moderator to the project (here, for example https://opin-dev.liqd.net/de/dashboard/dolorum-recusandae/projects/ducimus-labore-unde/users), I click on the search result, but the user is not added. Tested in Safari and Firefox, both don’t work.

**Comment by slomo** [comment]
Fixed by #693
