### ISSUE TITLE
Make project tiles work for words > 17 chars

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#681]
When words in titles have more than 17 characters, they are not shown properly anymore in our project titles on opin-dev. With the new typeface, I think we can make the text size smaller and allow more characters. Especially German and maybe some other European languages easily surpass 18 characters on many words. 

![bildschirmfoto 2017-02-16 um 17 30 01](https://cloud.githubusercontent.com/assets/15341015/23030390/e9e12984-f46d-11e6-9575-a4fd3ab6241f.png)

**Comment by rittermo** [comment]
@damusp Could you make a suggestion for text size?

**Comment by damusp** [comment]
for this one I suggest using $font-size-medium (18px) instead of -large (24px). 

There are probably some other cases where we will need to adjust the font sizes and weights, but this one is certainly the most striking.

**Comment by slomo** [comment]
Are we than waiting for the issue making tiles works for words > 23 characters :smile:

**Comment by rittermo** [comment]
I know it sounds random, @slomo, but I read that the maximum length of words in German scientific texts hovers around 18 characters. And I just thought, it won’t get much more complicated than German science books, so why not use the worst case scenario. I just can’t find my source for the 18 characters anymore. :D

**Comment by rittermo** [comment]
Besides, let’s all be thankful that no one asks us to cope with German beauties like this word on our platform: Rindfleischetikettierungsüberwachungsaufgabenübertragungsgesetz (67 characters!). Although, since we are building a platform for political participation, maybe we should consider them? ;)
