### ISSUE TITLE
Make project tiles work for long organization names

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#682]
Currently, organization names in the project tiles that break into two lines flow around the logo of the orga in a strange way. Please fix.

![bildschirmfoto 2017-02-16 um 17 33 26](https://cloud.githubusercontent.com/assets/15341015/23030473/2e4f34da-f46e-11e6-9147-8a787246eae5.png)

**Comment by MagdaN** [comment]
@rittermo should this also be a link that links to the organisation
