### ISSUE TITLE
Offline Downloads: Extend supported file types

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#702]
To make it possible to upload some more files related to offline events, we should allow more file types. I would like extend the support by adding:

- .doc, .docx
- .txt
- .md
- .xls, .xlsx
- .ppt, .pptx

We also should state in a small help text over the file upload input the supported file types and max file size: “Here you can upload a document that you want to share with your participants. The supported file types are <list of file types>. The max file size is <x>MB.”

**Comment by MagdaN** [comment]
OK, thats different from the userstory
