### ISSUE TITLE
Offline Downloads: 413 Request Entity…

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#704]
When I try to upload a document that is too large, an error page with a 413 error pops up. Can we change this to a validation error inside the form just as we do it in the dashboard, for example?
![bildschirmfoto 2017-02-23 um 13 53 21](https://cloud.githubusercontent.com/assets/15341015/23260696/59a25576-f9d3-11e6-9497-84a20e1e9869.png)

**Comment by MagdaN** [comment]
@rittermo can you remember how big the file was? Maybe that is an error that comes from the server, because I added file size validation.

@slomo what do you think?

**Comment by MagdaN** [comment]
@rittermo this error comes from the server setting, in code a maxsize of 5 MB is allowed and the server allows 10 MB, so if you add a file with a size of 6 MB the validation will work but if you add a file bigger than 10 MB the server error will occur, as the server will validate before our code. There are two options:

1) extend the max size of the server
2) check file size in javascript

For now we did 1), which means the error can still occur. For 2) I would suggest to add a userstory.

**Comment by slomo** [comment]
I increased the allowed maximal upload on the server to 100MB. We agreed in an offline meeting to add a story for implementing the size check in javascript.
