### ISSUE TITLE
Dashboard | Better display of error Message for file upload

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#737]
Hey, hey, the error message when the picture upload fails would take benefit from somewhat more attention, so that the user can see it much better (e.g. red frame). Thanks! 

![bildschirmfoto 2017-03-08 um 11 26 31](https://cloud.githubusercontent.com/assets/13625047/23706031/cce8cc70-040c-11e7-9354-91387754fb42.png)

**Comment by slomo** [comment]
This has been fixed in #670
