### ISSUE TITLE
DST | Small changes in "Fine tuning" section 

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#738]
Hey there, Nicolas sent some change request for text in the section "fine tuning" for the DST:
- [x] "Collection of commented ideas" instead of "Collection of ideas or arguments"
- [x] "Both" instead of "Weighted arguments"
- [x]  "1-2 participative projects" instead of "1-2 partcipative projects"
- [x]  "How motivated are your participants to take part in a participative process?" instead of "How dedicated are your participants?"
- [x] Add a 5th answer option "I don't know" in the motivation section
- [ ] Design: All answering options should start on the same height
- [x] One answer per section should be mandatory; it should not be possible to click on "results" without having clicked on one of the answering options

![bildschirmfoto 2017-03-08 um 15 16 36](https://cloud.githubusercontent.com/assets/13625047/23707817/02d29c88-0414-11e7-94fa-d159870abcb8.png)

**Comment by slomo** [comment]
I talked to @damusp last week about the height of those radio buttons and he was okay with it. Since he is the Designer of that view, he is in charge here.

**Comment by damusp** [comment]
I think changing this would not pay off.

In my opinion it looks decent as it is, even if it's not visually perfect due to differing text lengths.

Making the answers start at the same height will rip strange holes of white space between questions and answers, so this is not really perfect either.
