### ISSUE TITLE
DST | Add sentence on result page above templates

### ISSUE THREAD

**Issue by NadineKarbach** [liqd/euth_wagtail#741]
Hey, hey, last but not least, here the final request from Nicolas for changes on the DST: On the result page he thinks it is nice to have a headline saying "The following participative processes are suitable for your project". Thanks!

![bildschirmfoto 2017-03-08 um 16 01 55](https://cloud.githubusercontent.com/assets/13625047/23709345/68aa3250-0419-11e7-9215-7139754a1a9f.png)

**Comment by slomo** [comment]
This view is already different on opin-dev.

![](http://image.prntscr.com/image/68e3e6715abc4a6f8efcb738df8f1503.png)

I consider this issue therefore solved.
