### ISSUE TITLE
Should Comments be editable when they are flagged deleted

### ISSUE THREAD

**Issue by MagdaN** [liqd/euth_wagtail#77]
This is not possible via the current frontend but API allows it. There are two possibilities, disable it only via API but not in general or disable it in general

**Comment by nicoladimarco** [comment]
Comment should NOT be editable when they are flagged as deleted

**Comment by slomo** [comment]
I think the comment is currently not editable.The comment widget doesn't allow it, you can do it from the django admin, but the text will be reseted upon saving.

**Comment by MagdaN** [comment]
If you remove the reomve or censored flag in the admin you can of course change the text of the comment in the admin
