### ISSUE TITLE
Registration email: Logo off center after resizing

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#82]
In Mac OS X Mail.app Version 9.1 the logo jumps off center when you resize the email window.

![mail_opin2](https://cloud.githubusercontent.com/assets/15341015/16455362/49e3a99e-3e14-11e6-8ac8-98065396adbd.png)

**Comment by MagdaN** [comment]
@rittermo can you test?

**Comment by rittermo** [comment]
@MagdaN I tested it with the password reset email and there it still didn’t work. Was the change implemented for that type of email too or do I need to register again?

**Comment by rittermo** [comment]
Logo stays centered now! Thanks!
