### ISSUE TITLE
Registration email: Too many links are rendered

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#83]
In my Mac OS mail client (Mail.app Version 9.1) all the URLs are rendered as links which makes it hard to spot the actual activation link. I would suggest to either visually emphasize the activation link with a box and/or remove some of the other URLs.

![mail_opin_links](https://cloud.githubusercontent.com/assets/15341015/16455501/db6af1ce-3e14-11e6-9f92-e6201dc9297d.png)

**Comment by MagdaN** [comment]
I had the same problems in Chrome

**Comment by localgrr** [comment]
![screenshot-mail google com 2016-07-05 15-19-20](https://cloud.githubusercontent.com/assets/701632/16586000/e839e3f2-42c3-11e6-9fd9-3bf82b9010c4.png)
Any good? @rittermo @MagdaN

**Comment by localgrr** [comment]
Another option is @slomo offered to remove the other links, idk how to do this

**Comment by nicoladimarco** [comment]
I would do something like:

LOGO
Thanks for registering.
Please activate your account!
{BUTTON}
If the button above doesn´t work correctly please click or copy-paste the following link
{LINK}
