### ISSUE TITLE
Answer button seems a little lost 

### ISSUE THREAD

**Issue by rittermo** [liqd/euth_wagtail#89]
The answer button for comment replies seems a little lost in white space and it is hard to see which comment the button belongs to. I think we should reconsider the position of the reply button and maybe put it to the left. Or we leave it out and merge it with the “view 10 replies“ button in Nico’s design. That could also be an option, since we show the reply text area by default anyway.

![bildschirmfoto 2016-06-30 um 10 39 40](https://cloud.githubusercontent.com/assets/15341015/16482332/93b09528-3eaf-11e6-81e2-712f671c5a47.png)

**Comment by rittermo** [comment]
@nicoladimarco Could you take a look at that again?

**Comment by localgrr** [comment]
I can make it narrower

**Comment by NadineKarbach** [comment]
@localgrr @MagdaN Hi, can we change "anwser" to "answer"? Hope that comment is not too late on this
